Translating CONTRIBUTING.md to portuguese
fga-gpp-mds/2017.2-Grupo8 pull request #112
Opened 2017-11-10 17:33 UTC by leossb36

Signed-off-by: Leonardo Dos Santos Silva Barreiros <leossb36@gmail.com>

## Mudanças Propostas

Traduzindo o arquivo Contributing.md para português

## Tipo de Mudança

Que tipo de mudanças este Pull Request introduz ao Falko?
_Marque um `x` ao que se aplicar_

- [ ] Conserto de Bug
- [ ] Nova Feature

## Checklist

_Marque um `x`ao que se aplicar. Se você não tiver certeza sobre algum dos tópicos, não hesite em perguntar. Estamos aqui para ajudar!_

- [x] O nome do pull request deve ser auto-explicativo e deve estar em português.
- [x] Os commits seguem a [política de commits do repositório](https://github.com/fga-gpp-mds/Falko-2017.2-BackEnd/wiki/Plano-de-Gerenciamento-de-Configura%C3%A7%C3%A3o-de-Software#41---pol%C3%ADtica-de-commits).
- [ ] Não há erros no rubocop.
- [ ] A build está passando (testes, code climate e codacy).
- [ ] O pull request está linkado à uma issue existente.
- [ ] Foram criados seeds para as novas User Stories.

## Outros Comentários
Se for uma mudança relativamente grande/complexa e você tiver algum comentário/pergunta a fazer, explicação de sua escolha da sua solução ou qualquer coisa que ache relevante, não hesite em compartilhar.

2017-11-10 18:58 UTC, alaxalves commented
Pode deixar tudo em português @leossb36

2017-11-10 19:45 UTC, alaxalves requested changes
Pode deixar em portugues apenas @leossb36

2017-11-10 19:46 UTC, alaxalves commented
Pode colocar o nome do PR em portugues também

2017-11-11 02:28 UTC, MatheusRich commented on CONTRIBUTING.md
>  You can find more detailed info about our Code Of Conduct at the file CODE_OF_CONDUCT.md, that can be
Essa parte não dá pra traduzir?

2017-11-13 22:51 UTC, MatheusRich approved these changes

2017-11-14 12:20 UTC, alaxalves approved these changes

2017-11-14 12:21 UTC, merged

2017-11-14 17:44 UTC, cantuariavc commented
Resolve a issue #104