Dependencias de datas entre Sprint e Releases
fga-gpp-mds/2017.2-Grupo8 pull request #124
Opened 2017-11-13 22:03 UTC by Matheus456

## Mudanças Propostas

Arrumando a dependencias de datas entre Sprint e Releases

## Tipo de Mudança

Que tipo de mudanças este Pull Request introduz ao Falko?
_Marque um `x` ao que se aplicar_

- [x] Conserto de Bug
- [ ] Nova Feature

## Checklist

_Marque um `x`ao que se aplicar. Se você não tiver certeza sobre algum dos tópicos, não hesite em perguntar. Estamos aqui para ajudar!_

- [x] O nome do pull request deve ser auto-explicativo e deve estar em português.
- [x] Os commits seguem a [política de commits do repositório](https://github.com/fga-gpp-mds/Falko-2017.2-BackEnd/wiki/Plano-de-Gerenciamento-de-Configura%C3%A7%C3%A3o-de-Software#41---pol%C3%ADtica-de-commits).
- [ ] Não há erros no rubocop.
- [ ] A build está passando (testes, code climate e codacy).
- [x] O pull request está linkado à uma issue existente.
- [ ] Foram criados seeds para as novas User Stories.

## Outros Comentários
Se for uma mudança relativamente grande/complexa e você tiver algum comentário/pergunta a fazer, explicação de sua escolha da sua solução ou qualquer coisa que ache relevante, não hesite em compartilhar.

2017-11-13 23:55 UTC, MatheusRich requested changes
@Matheus456  Você verificou se os seeds foram corrigidos para criar sprints corretamente?

2017-11-13 23:55 UTC, MatheusRich commented on app/controllers/sprints_controller.rb
> +      render json: { error: "Can not create a sprint outside the range of a release" }, status: 406
O ideal sempre é não colocar o código do erro, mas sim o seu nome. 
Ex:
`status: :unprocessable_entity`

2017-11-14 02:42 UTC, Matheus456 commented on app/controllers/sprints_controller.rb
> +      render json: { error: "Can not create a sprint outside the range of a release" }, status: 406
Problema resolvido!

2017-11-14 02:44 UTC, Matheus456 commented on app/controllers/sprints_controller.rb
> +      render json: { error: "Can not create a sprint outside the range of a release" }, status: 406
Na verdade, vou olhar essa questão do seeds

2017-11-14 02:52 UTC, Matheus456 commented on app/controllers/sprints_controller.rb
> +      render json: { error: "Can not create a sprint outside the range of a release" }, status: 406
@MatheusRich Os seeds já estão corretos!

2017-11-14 12:56 UTC, MatheusRich requested changes

2017-11-14 12:56 UTC, MatheusRich commented on test/controllers/sprints_controller_test.rb
> +        "description": "Descrição da sprint",
Não adicionar textos em português.

2017-11-14 12:56 UTC, MatheusRich commented on test/controllers/sprints_controller_test.rb
> +        "description": "Descrição da sprint",
Não adicionar textos em português.

2017-11-14 12:57 UTC, alaxalves commented
@Matheus456 Tem coisa em portugues amorzin

2017-11-14 13:00 UTC, alaxalves requested changes

2017-11-14 13:00 UTC, alaxalves commented on test/controllers/sprints_controller_test.rb
> +        "name": "Saaaaa",
Coloca nomes mais significativos

2017-11-14 15:58 UTC, Matheus456 commented
Ok lindos! Vou arrumar ;)

2017-11-14 16:09 UTC, Matheus456 commented
@alaxalves e @MatheusRich, os textos foram arrumados!

2017-11-14 16:34 UTC, MatheusRich submitted a review, later dismissed

2017-11-14 19:13 UTC, alaxalves commented on test/controllers/revisions_controller_test.rb
> +      undone_report: ["History was not made us22"],
O correto aqui seria "Story was not made"

2017-11-14 19:14 UTC, alaxalves commented on test/controllers/revisions_controller_test.rb
> +      done_report: ["A us14 story was made"],
O correto aqui seria "us14 was made"

2017-11-17 19:33 UTC, MatheusRich approved these changes

2017-11-17 19:34 UTC, alaxalves approved these changes

2017-11-17 19:41 UTC, merged

2017-11-17 19:44 UTC, alaxalves commented
Lembra de seguir o padrão de commits.

2017-11-17 21:36 UTC, cantuariavc commented
Resolve a issue #120