Adicionando método de linha ideal no array de burndown
fga-gpp-mds/2017.2-Grupo8 pull request #169
Opened 2017-12-05 17:14 UTC by MateusO97

## Mudanças Propostas

Adicionando campo de linha ideal ao array de burndown para cria-la no frontend.

## Tipo de Mudança

Que tipo de mudanças este Pull Request introduz ao Falko?
_Marque um `x` ao que se aplicar_

- [ ] Conserto de Bug
- [x] Nova Feature

## Checklist

_Marque um `x`ao que se aplicar. Se você não tiver certeza sobre algum dos tópicos, não hesite em perguntar. Estamos aqui para ajudar!_

- [x] O nome do pull request deve ser auto-explicativo e deve estar em português.
- [x] Os commits seguem a [política de commits do repositório](https://github.com/fga-gpp-mds/Falko-2017.2-BackEnd/wiki/Plano-de-Gerenciamento-de-Configura%C3%A7%C3%A3o-de-Software#41---pol%C3%ADtica-de-commits).
- [x] Não há erros no rubocop.
- [x] A build está passando (testes, code climate e codacy).
- [x] O pull request está linkado à uma issue existente.
- [x] Foram criados seeds para as novas User Stories.

2017-12-05 17:45 UTC, alaxalves requested changes

2017-12-05 17:45 UTC, alaxalves commented on app/controllers/sprints_controller.rb
> +      date_axes = []
O correto é date_axis :dagger:

2017-12-05 17:46 UTC, alaxalves commented on app/controllers/sprints_controller.rb
> +      date_axes = []
Assim como nos outros lugares que está escrito _axes_, o correto seria _axis_.

2017-12-06 01:51 UTC, MateusO97 commented
@alaxalves Concertei os nomes, obrigado pelo aviso!

2017-12-06 13:31 UTC, MatheusRich commented
@MateusO97 Nenhum teste deve ser feito/alterado depois dessas modificações?

2017-12-07 12:01 UTC, alaxalves approved these changes

2017-12-07 12:05 UTC, alaxalves commented
@MatheusRich Acredito que apenas devem ser adicionados novos testes, já que foi acrescentado um novo atributo.

2017-12-07 18:17 UTC, MateusO97 commented
@alaxalves os testes que estavam feitos já cobrem o novo atributo que adicionamos, então não é necessário fazer novos

2017-12-09 16:47 UTC, ThalissonMelo approved these changes

2017-12-09 16:47 UTC, merged