Us21 manter nota
fga-gpp-mds/2017.2-Grupo8 pull request #175
Opened 2017-12-10 02:08 UTC by pedrokelvin

## Mudanças Propostas

História de usuário Manter Nota

## Tipo de Mudança

Que tipo de mudanças este Pull Request introduz ao Falko?
_Marque um `x` ao que se aplicar_

- [ ] Conserto de Bug
- [x] Nova Feature

## Checklist

_Marque um `x`ao que se aplicar. Se você não tiver certeza sobre algum dos tópicos, não hesite em perguntar. Estamos aqui para ajudar!_

- [x] O nome do pull request deve ser auto-explicativo e deve estar em português.
- [x] Os commits seguem a [política de commits do repositório](https://github.com/fga-gpp-mds/Falko-2017.2-BackEnd/wiki/Plano-de-Gerenciamento-de-Configura%C3%A7%C3%A3o-de-Software#41---pol%C3%ADtica-de-commits).
- [ ] Não há erros no rubocop.
- [ ] A build está passando (testes, code climate e codacy).
- [x] O pull request está linkado à uma issue existente.
- [ ] Foram criados seeds para as novas User Stories.

## Outros Comentários

2017-12-11 13:24 UTC, alaxalves commented
![image](https://user-images.githubusercontent.com/19597045/33833094-a26975ba-de65-11e7-96df-4d8ced4497ce.png)

Acredito que a solução pra esse erro seria agrupar os atributos semelhantes em um objeto apenas, porém iríamos perder em legibilidade. Vou ignorar essa _issue_.

2017-12-13 21:32 UTC, alaxalves requested changes

2017-12-13 21:32 UTC, alaxalves commented on app/controllers/grades_controller.rb
> +    # rescue HasNoSprints
pq vcs comentaram isso ??

2017-12-13 21:32 UTC, alaxalves commented on test/models/grade_test.rb
> +      description: "Esse projeto faz parte da disciplina MDS.",
E isso aqui em portugues??

2017-12-13 21:32 UTC, alaxalves commented on test/models/grade_test.rb
> +      description: "Essa sprint",
Portugues :D

2017-12-13 21:32 UTC, alaxalves commented on test/controllers/grades_controller_test.rb
> +      name: "Futebol",
Portuguessss

2017-12-13 21:32 UTC, alaxalves commented on app/helpers/validations_helper.rb
> +  def validate_grade(id, grade_id)
Que _id_ é esse?

2017-12-13 21:49 UTC, pedrokelvin commented on app/controllers/grades_controller.rb
> +    # rescue HasNoSprints
A gente tava fazendo uns testes pra lançar exceção mas não deu certo. Vou retirar

2017-12-13 22:33 UTC, alaxalves commented on app/helpers/validations_helper.rb
> +  def validate_grade(id, grade_id)
@pedrokelvin Digue que _id_ é esse?

2017-12-13 23:42 UTC, alaxalves approved these changes

2017-12-13 23:43 UTC, merged