Issue 68 - Adicionando número de Sprints na releases
fga-gpp-mds/2017.2-Grupo8 pull request #73
Opened 2017-11-03 16:16 UTC by Matheus456

## Mudanças Propostas

Descreva brevemente as mudanças feitas. Tenha certeza que linkou o pull request à uma issue existente.

## Tipo de Mudança

Que tipo de mudanças este Pull Request introduz ao Falko?
_Marque um `x` ao que se aplicar_

- [ ] Conserto de Bug
- [x] Nova Feature

## Checklist

_Marque um `x`ao que se aplicar. Se você não tiver certeza sobre algum dos tópicos, não hesite em perguntar. Estamos aqui para ajudar!_

- [x] O nome do pull request deve ser auto-explicativo e deve estar em português.
- [x] Os commits seguem a [política de commits do repositório](https://github.com/fga-gpp-mds/Falko-2017.2-BackEnd/wiki/Plano-de-Gerenciamento-de-Configura%C3%A7%C3%A3o-de-Software#41---pol%C3%ADtica-de-commits).
- [ ] Não há erros no rubocop.
- [ ] A build está passando (testes, code climate e codacy).
- [x] O pull request está linkado à uma issue existente.

## Outros Comentários
Se for uma mudança relativamente grande/complexa e você tiver algum comentário/pergunta a fazer, explicação de sua escolha da sua solução ou qualquer coisa que ache relevante, não hesite em compartilhar.

2017-11-04 17:20 UTC, alaxalves commented
Ei jovem @Matheus456 atualiza o template do PR por favor.

2017-11-04 17:25 UTC, alaxalves commented
Me parece legal o que você fez, mas tive a impressão de que os dois métodos criados podem ser abstraídos em uma Helper, não acha?? @Matheus456 
Confirma se eu to certo, @MatheusRich @MartinsLucas @matheussbernardo

2017-11-05 02:22 UTC, MatheusRich requested changes
O mesmo método está criado em dois arquivos diferentes. Utilize uma helper para evitar a repetição de código.

2017-11-05 02:37 UTC, MatheusRich commented
Outra coisa: aparentemente o método apenas atualiza o valor de uma variável, acredito que o nome do método poderia ser **update_amount_of_sprints**, pois ficaria mais claro o que o método faz.

2017-11-05 02:59 UTC, Matheus456 commented
Certo, não tinha conhecimento da helper. Obrigado pelas dicas, fiz as alterações!

2017-11-05 12:43 UTC, alaxalves commented
Beleza! Vou aceitar, mas é necessário que sejam feitos testes relacionados a esse novo método depois :100: @Matheus456

2017-11-05 12:44 UTC, alaxalves submitted a review, later dismissed

2017-11-05 17:36 UTC, MatheusRich commented
@Matheus456 Há um pequeno erro de linter no seu pull request. Além disso, ele não está conectado a nenhuma issue!

2017-11-05 17:38 UTC, Matheus456 commented
Estou arrumando isso agora mesmo

2017-11-05 17:49 UTC, Matheus456 commented
@MatheusRich Agora está pronto!

2017-11-05 18:14 UTC, Matheus456 commented
@MatheusRich Para mim ele estava conectado com uma issue, tentei procurar aqui para conectar e não encontrei a issue que eu queria.

2017-11-05 19:05 UTC, alaxalves commented
Resolve a Issue https://github.com/fga-gpp-mds/Falko-2017.2-BackEnd/issues/68

2017-11-05 19:06 UTC, alaxalves approved these changes

2017-11-05 19:07 UTC, merged